name: fetosense_mis
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^15.0.0
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^10.6.0
  excel: ^3.0.0
  path_provider: ^2.0.14
  permission_handler: ^11.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login/fetosense.png

 